/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisguilherme.sistemaclinicas.back.front;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Guilg
 */
public class consultarEnfermeiroPanel extends javax.swing.JPanel {

    private CardLayout cl;
    private javax.swing.JPanel container;
    
    public consultarEnfermeiroPanel(CardLayout cl, javax.swing.JPanel container) {
        initComponents();
        setCl(cl);
        setContainer(container);
    }
    public CardLayout getCl() {
        return cl;
    }

    public void setCl(CardLayout cl) {
        this.cl = cl;
    }

    public JPanel getContainer() {
        return container;
    }

    public void setContainer(JPanel container) {
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarEnfermeiro = new javax.swing.JPanel();
        nomeFieldEnfermeiro = new javax.swing.JTextField();
        nomeLabelEnfermeiro = new javax.swing.JLabel();
        nascimentoLabelEnfermeiro = new javax.swing.JLabel();
        ruaLabelEnfermeiro = new javax.swing.JLabel();
        ruaFieldEnfermeiro = new javax.swing.JTextField();
        numeroLabelEnfermeiro = new javax.swing.JLabel();
        numeroFieldEnfermeiro = new javax.swing.JTextField();
        bairroLabelEnfermeiro = new javax.swing.JLabel();
        estadoFieldEnfermeiro = new javax.swing.JTextField();
        estadoLabelEnfermeiro = new javax.swing.JLabel();
        cidadeFieldEnfermeiro = new javax.swing.JTextField();
        cidadeLabelEnfermeiro = new javax.swing.JLabel();
        nascimentoFieldEnfermeiro = new com.toedter.calendar.JDateChooser();
        bairroFieldEnfermeiro = new javax.swing.JTextField();
        CEPFieldlEnfermeiro = new javax.swing.JTextField();
        CEPLabelEnfermeiro = new javax.swing.JLabel();
        telefoneFieldEnfermeiro = new javax.swing.JTextField();
        telefoneLabelEnfermeiro = new javax.swing.JLabel();
        celularFieldEnfermeiro = new javax.swing.JTextField();
        celularLabelEnfermeiro = new javax.swing.JLabel();
        emailLabelEnfermeiro = new javax.swing.JLabel();
        emailFieldEnfermeiro = new javax.swing.JTextField();
        generoLabelEnfermeiro = new javax.swing.JLabel();
        generoComboBoxEnfermeiro = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        setorLabelEnfermeiro = new javax.swing.JLabel();
        setorFieldEnfermeiro = new javax.swing.JTextField();
        chFieldEnfermeiro = new javax.swing.JTextField();
        chLabelEnfermeiro = new javax.swing.JLabel();
        idFieldEnfermeiro = new javax.swing.JTextField();
        idLabelEnfermeiro = new javax.swing.JLabel();
        rxLabelEnfermeiro = new javax.swing.JLabel();
        rxComboBoxEnfermeiro = new javax.swing.JComboBox<>();
        backBtnEnfermeiro = new javax.swing.JButton();
        selectionComboBoxEnfermeiro = new javax.swing.JComboBox<>();
        selectionLabelEnfermeiro = new javax.swing.JLabel();

        nomeLabelEnfermeiro.setText("Nome");

        nascimentoLabelEnfermeiro.setText("Data de Nascimento");

        ruaLabelEnfermeiro.setText("Rua");

        numeroLabelEnfermeiro.setText("Numero");

        bairroLabelEnfermeiro.setText("Bairro");

        estadoLabelEnfermeiro.setText("Estado");

        cidadeLabelEnfermeiro.setText("Cidade");

        CEPLabelEnfermeiro.setText("CEP");

        telefoneLabelEnfermeiro.setText("Telefone");

        celularLabelEnfermeiro.setText("Celular");

        emailLabelEnfermeiro.setText("Email");

        generoLabelEnfermeiro.setText("Genero");

        generoComboBoxEnfermeiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        generoComboBoxEnfermeiro.setToolTipText("");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Informações Gerais");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Informações Especificas");

        setorLabelEnfermeiro.setText("Setor");

        chLabelEnfermeiro.setText("Carga Horaria Semanal");

        idLabelEnfermeiro.setText("Id Enfermeiro");

        rxLabelEnfermeiro.setText("Treinado em Raio X?");

        rxComboBoxEnfermeiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Treinado", "Não Treinado" }));

        backBtnEnfermeiro.setText("<----");
        backBtnEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnEnfermeiroActionPerformed(evt);
            }
        });

        selectionLabelEnfermeiro.setText("Enfermeiro");

        javax.swing.GroupLayout cadastrarEnfermeiroLayout = new javax.swing.GroupLayout(cadastrarEnfermeiro);
        cadastrarEnfermeiro.setLayout(cadastrarEnfermeiroLayout);
        cadastrarEnfermeiroLayout.setHorizontalGroup(
            cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarEnfermeiroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backBtnEnfermeiro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarEnfermeiroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectionLabelEnfermeiro)
                    .addComponent(selectionComboBoxEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(231, 231, 231))
            .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(numeroLabelEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ruaLabelEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nascimentoLabelEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeLabelEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ruaFieldEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(numeroFieldEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nascimentoFieldEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomeFieldEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(setorLabelEnfermeiro)
                    .addComponent(setorFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chLabelEnfermeiro)
                    .addComponent(chFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                        .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLabelEnfermeiro)
                                    .addComponent(rxLabelEnfermeiro)
                                    .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(idFieldEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rxComboBoxEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE))
                                    .addComponent(CEPLabelEnfermeiro)
                                    .addComponent(estadoLabelEnfermeiro)
                                    .addComponent(cidadeLabelEnfermeiro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarEnfermeiroLayout.createSequentialGroup()
                                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cidadeFieldEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estadoFieldEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CEPFieldlEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(bairroFieldEnfermeiro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastrarEnfermeiroLayout.createSequentialGroup()
                                        .addComponent(bairroLabelEnfermeiro)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(68, 68, 68)))
                        .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(telefoneLabelEnfermeiro)
                                .addComponent(telefoneFieldEnfermeiro)
                                .addComponent(celularLabelEnfermeiro)
                                .addComponent(celularFieldEnfermeiro)
                                .addComponent(emailLabelEnfermeiro)
                                .addComponent(emailFieldEnfermeiro)
                                .addComponent(generoComboBoxEnfermeiro, javax.swing.GroupLayout.Alignment.TRAILING, 0, 170, Short.MAX_VALUE))
                            .addComponent(generoLabelEnfermeiro))
                        .addGap(86, 86, 86))))
        );
        cadastrarEnfermeiroLayout.setVerticalGroup(
            cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backBtnEnfermeiro)
                .addGap(32, 32, 32)
                .addComponent(selectionLabelEnfermeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionComboBoxEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarEnfermeiroLayout.createSequentialGroup()
                                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                                        .addComponent(telefoneLabelEnfermeiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(telefoneFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                                        .addComponent(bairroLabelEnfermeiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bairroFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoLabelEnfermeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarEnfermeiroLayout.createSequentialGroup()
                                .addComponent(celularLabelEnfermeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celularFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nomeLabelEnfermeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nascimentoLabelEnfermeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nascimentoFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaLabelEnfermeiro)
                    .addComponent(cidadeLabelEnfermeiro)
                    .addComponent(emailLabelEnfermeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabelEnfermeiro)
                    .addComponent(CEPLabelEnfermeiro)
                    .addComponent(generoLabelEnfermeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CEPFieldlEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoComboBoxEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(9, 9, 9)
                .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cadastrarEnfermeiroLayout.createSequentialGroup()
                        .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setorLabelEnfermeiro)
                            .addComponent(idLabelEnfermeiro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setorFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cadastrarEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chLabelEnfermeiro)
                            .addComponent(rxLabelEnfermeiro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rxComboBoxEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(chFieldEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cadastrarEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cadastrarEnfermeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnEnfermeiroActionPerformed
        cl.show(container,"mainWindow");
    }//GEN-LAST:event_backBtnEnfermeiroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CEPFieldlEnfermeiro;
    private javax.swing.JLabel CEPLabelEnfermeiro;
    private javax.swing.JButton backBtnEnfermeiro;
    private javax.swing.JTextField bairroFieldEnfermeiro;
    private javax.swing.JLabel bairroLabelEnfermeiro;
    private javax.swing.JPanel cadastrarEnfermeiro;
    private javax.swing.JTextField celularFieldEnfermeiro;
    private javax.swing.JLabel celularLabelEnfermeiro;
    private javax.swing.JTextField chFieldEnfermeiro;
    private javax.swing.JLabel chLabelEnfermeiro;
    private javax.swing.JTextField cidadeFieldEnfermeiro;
    private javax.swing.JLabel cidadeLabelEnfermeiro;
    private javax.swing.JTextField emailFieldEnfermeiro;
    private javax.swing.JLabel emailLabelEnfermeiro;
    private javax.swing.JTextField estadoFieldEnfermeiro;
    private javax.swing.JLabel estadoLabelEnfermeiro;
    private javax.swing.JComboBox<String> generoComboBoxEnfermeiro;
    private javax.swing.JLabel generoLabelEnfermeiro;
    private javax.swing.JTextField idFieldEnfermeiro;
    private javax.swing.JLabel idLabelEnfermeiro;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private com.toedter.calendar.JDateChooser nascimentoFieldEnfermeiro;
    private javax.swing.JLabel nascimentoLabelEnfermeiro;
    private javax.swing.JTextField nomeFieldEnfermeiro;
    private javax.swing.JLabel nomeLabelEnfermeiro;
    private javax.swing.JTextField numeroFieldEnfermeiro;
    private javax.swing.JLabel numeroLabelEnfermeiro;
    private javax.swing.JTextField ruaFieldEnfermeiro;
    private javax.swing.JLabel ruaLabelEnfermeiro;
    private javax.swing.JComboBox<String> rxComboBoxEnfermeiro;
    private javax.swing.JLabel rxLabelEnfermeiro;
    private javax.swing.JComboBox<String> selectionComboBoxEnfermeiro;
    private javax.swing.JLabel selectionLabelEnfermeiro;
    private javax.swing.JTextField setorFieldEnfermeiro;
    private javax.swing.JLabel setorLabelEnfermeiro;
    private javax.swing.JTextField telefoneFieldEnfermeiro;
    private javax.swing.JLabel telefoneLabelEnfermeiro;
    // End of variables declaration//GEN-END:variables
}
