/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisguilherme.sistemaclinicas.back.front;

import com.luisguilherme.sistemaclinicas.back.ConsultaMedica;
import com.luisguilherme.sistemaclinicas.back.Medico;
import com.luisguilherme.sistemaclinicas.back.Paciente;
import com.luisguilherme.sistemaclinicas.back.SistemaClinicas;
import java.awt.CardLayout;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author souzlui03
 */
public class deletarConsultaMed extends CRUD_JPanel {

    /**
     * Creates new form deletarConsultaMed
     */
    private Paciente pacSelecionado;
    public deletarConsultaMed(CardLayout cl, JPanel container, SistemaClinicas back) {
        super(cl, container, back);
        initComponents();
        listPacientes(selecPacienteComboBox);
    }
    
    public Paciente getPacSelecionado() {
        return pacSelecionado;
    }

    public void setPacSelecionado(Paciente pacSelecionado) {
        this.pacSelecionado = pacSelecionado;
    }
    
    public void listPacientes(JComboBox cb){
        //carrega opções no comboBox
        cb.removeAllItems();
        for(Paciente e : getBack().getPacientes()){
            cb.addItem(e.getNomeCompleto());
        }
    }
    
    public void listConsultas(){
        //carrega opções no comboBox
        selecConsultaComboBox.removeAllItems();
        for(ConsultaMedica e : pacSelecionado.getHistoricoConsultasMedicas()){
            selecConsultaComboBox.addItem(Long.toString(e.getIdConsulta()));
        }
    }
    
    public void loadInfo(int index){
        
        ConsultaMedica cm = pacSelecionado.getHistoricoConsultasMedicas().get(index);
        pacienteComboBox.removeAllItems();
        medicoComboBox.removeAllItems();
        //populo paciente
        for(Paciente p : getBack().getPacientes()){
            if(p.getIdPaciente() == cm.getIdPaciente()){
                pacienteComboBox.addItem(p.getNomeCompleto());
                break;
            }
        }
        //populo medico
        for(Medico m : getBack().getMedicos()){
            if(m.getIdMedico()== cm.getIdMedico()){
                medicoComboBox.addItem(m.getNomeCompleto());
                break;
            }
        }
       //populo demais informações
       idField.setText(Long.toString(cm.getIdConsulta()));
       if(cm.isIndicacaoCirurgica()){
           cirurgiaComboBox.setSelectedIndex(0);
       }
       else{
           cirurgiaComboBox.setSelectedIndex(1);
       }
       diagnosticoField.setText(cm.getDiagnostico());
       prescricaoTextArea.setText(cm.getPrescricao());
       queixasTextArea.setText(cm.getExameQueixa());
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarConsultaMedica = new javax.swing.JPanel();
        pacienteLabel = new javax.swing.JLabel();
        medicoLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        medicoComboBox = new javax.swing.JComboBox<>();
        cirurgiaComboBox = new javax.swing.JComboBox<>();
        cirurgiaLabel = new javax.swing.JLabel();
        diagnosticoLabel = new javax.swing.JLabel();
        diagnosticoField = new javax.swing.JTextField();
        prescricaoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescricaoTextArea = new javax.swing.JTextArea();
        queixasLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        queixasTextArea = new javax.swing.JTextArea();
        pacienteComboBox = new javax.swing.JComboBox<>();
        selecPacienteComboBox = new javax.swing.JComboBox<>();
        selecConsultaComboBox = new javax.swing.JComboBox<>();
        selecPacienteLabel = new javax.swing.JLabel();
        selecConsultaLabel = new javax.swing.JLabel();
        deletarBtn = new javax.swing.JButton();

        pacienteLabel.setText("Paciente");

        medicoLabel.setText("Medico");

        idField.setEditable(false);
        idField.setFocusable(false);

        idLabel.setText("Id Consulta");

        backBtn.setText("<----");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        medicoComboBox.setEnabled(false);

        cirurgiaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        cirurgiaComboBox.setEnabled(false);

        cirurgiaLabel.setText("Indicação Cirurgica?");

        diagnosticoLabel.setText("Diagnostico");

        diagnosticoField.setEditable(false);
        diagnosticoField.setFocusable(false);

        prescricaoLabel.setText("Precrição");

        prescricaoTextArea.setEditable(false);
        prescricaoTextArea.setColumns(20);
        prescricaoTextArea.setRows(5);
        prescricaoTextArea.setEnabled(false);
        jScrollPane1.setViewportView(prescricaoTextArea);

        queixasLabel.setText("Queixas");

        queixasTextArea.setEditable(false);
        queixasTextArea.setColumns(20);
        queixasTextArea.setRows(5);
        queixasTextArea.setEnabled(false);
        jScrollPane2.setViewportView(queixasTextArea);

        pacienteComboBox.setEnabled(false);

        selecPacienteComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecPacienteComboBoxActionPerformed(evt);
            }
        });

        selecConsultaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecConsultaComboBoxActionPerformed(evt);
            }
        });

        selecPacienteLabel.setText("Selecione o Paciente");

        selecConsultaLabel.setText("Selecione a Consulta");

        deletarBtn.setText("Deletar");
        deletarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultarConsultaMedicaLayout = new javax.swing.GroupLayout(consultarConsultaMedica);
        consultarConsultaMedica.setLayout(consultarConsultaMedicaLayout);
        consultarConsultaMedicaLayout.setHorizontalGroup(
            consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarConsultaMedicaLayout.createSequentialGroup()
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarConsultaMedicaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backBtn))
                    .addGroup(consultarConsultaMedicaLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecPacienteLabel)
                            .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cirurgiaComboBox, 0, 170, Short.MAX_VALUE)
                                .addComponent(prescricaoLabel)
                                .addComponent(pacienteLabel)
                                .addComponent(cirurgiaLabel)
                                .addComponent(pacienteComboBox, 0, 170, Short.MAX_VALUE)
                                .addComponent(selecPacienteComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarConsultaMedicaLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarConsultaMedicaLayout.createSequentialGroup()
                                .addComponent(diagnosticoField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addGap(324, 324, 324))
                            .addGroup(consultarConsultaMedicaLayout.createSequentialGroup()
                                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(selecConsultaComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(diagnosticoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(medicoComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE)
                                        .addComponent(medicoLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(selecConsultaLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarConsultaMedicaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
            .addGroup(consultarConsultaMedicaLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarConsultaMedicaLayout.createSequentialGroup()
                        .addComponent(queixasLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarConsultaMedicaLayout.createSequentialGroup()
                        .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(consultarConsultaMedicaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLabel)
                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(97, 97, 97))))
        );
        consultarConsultaMedicaLayout.setVerticalGroup(
            consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarConsultaMedicaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(deletarBtn))
                .addGap(18, 18, 18)
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecPacienteLabel)
                    .addComponent(selecConsultaLabel))
                .addGap(5, 5, 5)
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecPacienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecConsultaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacienteLabel)
                    .addComponent(medicoLabel)
                    .addComponent(idLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cirurgiaLabel)
                    .addComponent(diagnosticoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultarConsultaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cirurgiaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diagnosticoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prescricaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(queixasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(consultarConsultaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(consultarConsultaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        getCl().show(getContainer(),"mainWindow");
    }//GEN-LAST:event_backBtnActionPerformed

    private void selecPacienteComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecPacienteComboBoxActionPerformed
        int index = selecPacienteComboBox.getSelectedIndex();
        pacSelecionado = getBack().getPacientes().get(index);
        listConsultas();

    }//GEN-LAST:event_selecPacienteComboBoxActionPerformed

    private void selecConsultaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecConsultaComboBoxActionPerformed
        int index = selecConsultaComboBox.getSelectedIndex();
        if(index != -1){
            loadInfo(index);
        }

    }//GEN-LAST:event_selecConsultaComboBoxActionPerformed

    private void deletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBtnActionPerformed
        //deleta e volta para a mainWindow
        int index = selecConsultaComboBox.getSelectedIndex();
        try{
            pacSelecionado.getHistoricoConsultasMedicas().remove(index);
        }
        catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Sem dados");
        }
        
        getCl().show(getContainer(),"mainWindow");
    }//GEN-LAST:event_deletarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> cirurgiaComboBox;
    private javax.swing.JLabel cirurgiaLabel;
    private javax.swing.JPanel consultarConsultaMedica;
    private javax.swing.JButton deletarBtn;
    private javax.swing.JTextField diagnosticoField;
    private javax.swing.JLabel diagnosticoLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> medicoComboBox;
    private javax.swing.JLabel medicoLabel;
    private javax.swing.JComboBox<String> pacienteComboBox;
    private javax.swing.JLabel pacienteLabel;
    private javax.swing.JLabel prescricaoLabel;
    private javax.swing.JTextArea prescricaoTextArea;
    private javax.swing.JLabel queixasLabel;
    private javax.swing.JTextArea queixasTextArea;
    private javax.swing.JComboBox<String> selecConsultaComboBox;
    private javax.swing.JLabel selecConsultaLabel;
    private javax.swing.JComboBox<String> selecPacienteComboBox;
    private javax.swing.JLabel selecPacienteLabel;
    // End of variables declaration//GEN-END:variables
}
