/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisguilherme.sistemaclinicas.back.front;

import com.luisguilherme.sistemaclinicas.back.SistemaClinicas;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Guilg
 */
public class menuExcel extends CRUD_JPanel {

    /**
     * Creates new form menuExcel
     */
    public menuExcel(CardLayout cl, JPanel container, SistemaClinicas back) {
        super(cl, container, back);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuExcel = new javax.swing.JPanel();
        caminhoLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        exportLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        caminhoField = new javax.swing.JTextField();
        caminhoBtn = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();

        caminhoLabel.setText("Caminho");

        nomeLabel.setText("Nome do Arquivo");

        exportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exportLabel.setText("Exportar");

        backBtn.setText("<----");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        caminhoField.setEditable(false);

        caminhoBtn.setText("📁");
        caminhoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminhoBtnActionPerformed(evt);
            }
        });

        exportBtn.setText("EXPORTAR");
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuExcelLayout = new javax.swing.GroupLayout(menuExcel);
        menuExcel.setLayout(menuExcelLayout);
        menuExcelLayout.setHorizontalGroup(
            menuExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuExcelLayout.createSequentialGroup()
                .addGroup(menuExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuExcelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(caminhoLabel))
                    .addGroup(menuExcelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backBtn)))
                .addGap(196, 196, 196)
                .addComponent(exportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(324, 324, 324))
            .addGroup(menuExcelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(menuExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeLabel)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuExcelLayout.createSequentialGroup()
                        .addComponent(caminhoField, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caminhoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(63, 63, 63)
                .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuExcelLayout.setVerticalGroup(
            menuExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuExcelLayout.createSequentialGroup()
                .addGroup(menuExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuExcelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(exportLabel))
                    .addGroup(menuExcelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backBtn)))
                .addGap(18, 18, 18)
                .addComponent(caminhoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuExcelLayout.createSequentialGroup()
                        .addGroup(menuExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caminhoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caminhoBtn))
                        .addGap(1, 1, 1)
                        .addComponent(nomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(426, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menuExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menuExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        getCl().show(getContainer(),"mainWindow");
        getContainer().remove(this);
    }//GEN-LAST:event_backBtnActionPerformed
    
    public boolean validar(){
        //valida todos os campos presentes no Jpanel e retorna falso caso algum
        //esteja invalido
        Validador v = new Validador();
        if(!v.validarCampo(caminhoField)){
            JOptionPane.showMessageDialog(null, "Caminho Invalido");
            return false;
        }
        if(!v.validarCampo(nomeField)){
            JOptionPane.showMessageDialog(null, "Nome Invalido");
            return false;
        }
        return true;
    }
    
    public void exportar(String caminho){
        try{
            getBack().getExportadorExcel().exportar(caminho);
            JOptionPane.showMessageDialog(null, "Gravação Concluida");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro na gravação");
        }
    }
    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        if(validar()){
            exportar(caminhoField.getText() + "\\" + nomeField.getText());
        }
        
    }//GEN-LAST:event_exportBtnActionPerformed

    private void caminhoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminhoBtnActionPerformed
        //instancio a janela
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = fileChooser.showOpenDialog(null);
        
        //checo se foi selecionado e adicionado ao campo bloqueado
        if (res == JFileChooser.APPROVE_OPTION){
            File selectedFolder = fileChooser.getSelectedFile();
            caminhoField.setText(selectedFolder.getAbsolutePath());
        } 
    }//GEN-LAST:event_caminhoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton caminhoBtn;
    private javax.swing.JTextField caminhoField;
    private javax.swing.JLabel caminhoLabel;
    private javax.swing.JButton exportBtn;
    private javax.swing.JLabel exportLabel;
    private javax.swing.JPanel menuExcel;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    // End of variables declaration//GEN-END:variables
}
